import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/page'
import { ChakraProvider } from '@chakra-ui/react'
import NavBar from './navBar/page'
import Footer from './footer/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <ChakraProvider>
            <body className={inter.className}>
               <div>
                  <Header />
                  <NavBar />
                  <div>
                     {children}
                  </div>
                  <div className='footer'>
                     <Footer />
                  </div>
               </div>
            </body>
         </ChakraProvider>
      </html>
   )
}
